spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/devsu
    username: root
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8061
  
rest-service:
  customer:
    base-url: http://localhost:8060
