version : '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/001_schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/002_tables_and_data.sql:/docker-entrypoint-initdb.d/2.sql"